//go:build linux

package service

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestSystemdUnitIsValid writes the unit exactly as Install would and
// has systemd itself check it.
//
// The unit is generated by string interpolation, and systemd's syntax
// has two traps that produce a unit which looks fine and simply never
// loads at the next login, with nothing to show why: "%" starts a
// specifier (an unknown one is a hard error), and ExecStart= splits on
// whitespace unless quoted. A user with a "%" or a space in their home
// directory or PATH would hit both.
func TestSystemdUnitIsValid(t *testing.T) {
	analyze, err := exec.LookPath("systemd-analyze")
	if err != nil {
		t.Skip("systemd-analyze not available")
	}

	home := t.TempDir()
	t.Setenv("HOME", home)
	// A home directory and PATH containing exactly the characters that
	// break naive interpolation.
	binary := filepath.Join(home, "odd dir 100%", "ccam")
	if err := os.MkdirAll(filepath.Dir(binary), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	t.Setenv("PATH", filepath.Dir(binary)+":/usr/bin:/bin")

	svc := &linuxService{generic{binaryPath: binary, port: 47932}}
	unitPath, err := svc.installSystemd(binary, 47932)
	if err != nil {
		t.Fatalf("installSystemd: %v", err)
	}

	unit, err := os.ReadFile(unitPath)
	if err != nil {
		t.Fatalf("reading unit: %v", err)
	}
	t.Logf("generated unit:\n%s", unit)

	out, err := exec.Command(analyze, "verify", unitPath).CombinedOutput()
	// systemd-analyze reports problems on stderr and exits non-zero for
	// real syntax errors. Warnings about a missing binary are expected
	// here (the path is a stub), so only fail on the syntax classes
	// this test exists for.
	report := string(out)
	t.Logf("systemd-analyze verify: %v\n%s", err, report)
	for _, bad := range []string{
		"Failed to resolve unit specifiers",
		"Invalid escape",
		"Executable path is not absolute",
		"Failed to parse",
	} {
		if strings.Contains(report, bad) {
			t.Errorf("systemd rejected the unit (%s):\n%s", bad, report)
		}
	}
}

// TestSystemdUnitEscapesSpecifiers pins the escaping directly, so the
// intent survives even where systemd-analyze isn't available.
func TestSystemdUnitEscapesSpecifiers(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", "/opt/100%stuff:/usr/bin")

	binary := filepath.Join(home, "ccam")
	svc := &linuxService{generic{binaryPath: binary, port: 47932}}
	unitPath, err := svc.installSystemd(binary, 47932)
	if err != nil {
		t.Fatalf("installSystemd: %v", err)
	}
	unit, err := os.ReadFile(unitPath)
	if err != nil {
		t.Fatalf("reading unit: %v", err)
	}

	if strings.Contains(string(unit), "100%stuff") {
		t.Errorf("a bare %% survived into the unit, systemd would treat it as a specifier:\n%s", unit)
	}
	if !strings.Contains(string(unit), "100%%stuff") {
		t.Errorf("expected the %% to be escaped as %%%%:\n%s", unit)
	}
	if !strings.Contains(string(unit), `ExecStart="`) {
		t.Errorf("ExecStart is not quoted, so a path with spaces would split:\n%s", unit)
	}
}
